---
abstract: 'IO::Async support for ZeroMQ'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  IO::Async::Loop: '0'
  Test::Most: '0'
  Test::Needs: '0'
  constant: '0'
  lib: '0'
  perl: '5.013002'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-ZMQ
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Fcntl: '0'
  IO::Async::Handle: '0'
  IO::Async::Notifier: '0'
  Module::Load: '0'
  Package::Stash: '0'
  base: '0'
  if: '0'
  perl: '5.013002'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/zmughal-CPAN/p5-Net-Async-ZMQ
  repository: https://github.com/zmughal-CPAN/p5-Net-Async-ZMQ.git
version: '0.002'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
