name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    env:
      AUTHOR_TESTING: 1
      ALT_ALIEN_ZMQ_BRANCH: master
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        perl: [ '5' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install ZMQ
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libczmq-dev
      - name: Install ZMQ
        if: matrix.os == 'macos-latest'
        run: |
          brew install zeromq
      - name: Install ZMQ
        if: matrix.os == 'windows-latest'
        run: |
          curl https://raw.githubusercontent.com/zmughal-CPAN/p5-Alt-Alien-ZMQ-Alien-ZMQ-latest/${{ env.ALT_ALIEN_ZMQ_BRANCH }}/maint/install-zmq-libzmq.pl | perl - --notest -- Alt::Alien::ZMQ::Alien::ZMQ::latest ZMQ::LibZMQ3 ZMQ::LibZMQ4 ZMQ::FFI
      - name: Install Perl deps
        run: |
          cpanm --notest --installdeps .
          cpanm --verbose --notest ZMQ::FFI ZMQ::LibZMQ3 ZMQ::LibZMQ4
      - name: Run tests
        run: |
          prove -lvr t
