name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    env:
      AUTHOR_TESTING: 1
      ALT_ALIEN_ZMQ_BRANCH: master
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        perl: [ '5' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os != 'windows-latest'
        with:
          perl-version: ${{ matrix.perl }}
      - name: Set up perl (Strawberry)
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os == 'windows-latest'
        with:
          distribution: 'strawberry'

      - run: perl -V
      - name: Install ZMQ
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libczmq-dev
      - name: Install ZMQ
        if: matrix.os == 'macos-latest'
        run: |
          brew install zeromq
      - name: Install ZMQ
        if: matrix.os == 'windows-latest'
        run: |
          curl https://raw.githubusercontent.com/zmughal-CPAN/p5-Alt-Alien-ZMQ-Alien-ZMQ-latest/${{ env.ALT_ALIEN_ZMQ_BRANCH }}/maint/install-zmq-libzmq.pl | perl - --notest -- Alt::Alien::ZMQ::Alien::ZMQ::latest ZMQ::LibZMQ3 ZMQ::LibZMQ4 ZMQ::FFI
          perl -MAlien::ZMQ::latest -E "say Alien::ZMQ::latest->bin_dir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          perl -pi -e 'my $im = q/libzmq.1.dylib/; s/\Q$im\E/libzmq.1.dylib libzmq.dll/' "$( perl -MZMQ::FFI::Util -E 'say $INC{q|ZMQ/FFI/Util.pm|}' )"
          type "$( perl -MZMQ::FFI::Util -E 'say $INC{q|ZMQ/FFI/Util.pm|}' )"
      - name: Install Perl deps
        run: |
          cpanm --notest --installdeps .
          cpanm --verbose --notest ZMQ::FFI ZMQ::LibZMQ3 ZMQ::LibZMQ4
      - name: Run tests
        run: |
          prove -lvr t
